Feat/websockets connect
kichel98/BlankietyGalantow pull request #15
Opened 2020-05-11 15:30 UTC by ketrab321

#14 
#13

2020-05-11 18:12 UTC, KyrietS requested changes
Jak klient zamknie kartę przeglądarki, to rzucany jest wyjątek i nie jest nigdzie łapany. Serwer po takim błędzie się psuje i nowi gracze nie mogą się już połączyć. Trzeba dodać jakąś minimalną obsługę zakończenia połączenia.

2020-05-11 18:15 UTC, KyrietS commented on blankiety_galantow/routers.py
> +        data = await websocket.receive_text()
Tutaj jest rzucany wyjątek jak gracz się rozłączy.

2020-05-12 15:17 UTC, KyrietS approved these changes
## Wprowadziłem poprawki
* Naprawiłem przechwytywanie wyjątku przy zerwaniu połączenia. Gracz jest teraz kulturalnie usuwany z pokoju, a reszta użytkowników dostaje komunikat serwerowy na czacie: "Gracz xxx opuścił pokój".
* Porozdzielałem odpowiedzialność na kilka klas i funkcji. Wyszła z tego fajna struktura.
* Dodałem klasę `Room`, która nie wie o innych pokojach. Zarządza jedynie "swoimi" graczami.
* Klasa `Server` od teraz zarządza pokojami `Room` i przydziela do nich graczy.
* Klasa `Player` to na razie taka "nakładka" na surowy Socket wyposażona w dwie funkcje umożliwiające wygodną pracę z nim.
* Wiele innych zmian

Zapoznajcie się ze zmianami jeśli macie ochotę i zgłaszajcie sugestie. Dzisiaj ten branch **musi** wejść, bo mamy REST API w kolejce z poprzedniego milestone do złączenia. Kod REST API trzeba przystosować, aby był kompatybilny z obecną strukturą.

2020-05-12 16:17 UTC, kichel98 requested changes
1. Mam pusty folder "classes", on jest do usunięcia?
2. Dobra robota, fajnie to zaczyna wyglądać 👍

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/app.py
> +# Creating FastApi instance and mounting static files
Dzięki za komentarze, których ja nie zrobiłem 👍 Biję się w pierś

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/resources/game/js/main.js
> +    data = JSON.parse(event.data)
Lepiej dać `let` albo `const` przed `data`.

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/resources/game/js/main.js
> +socket = connect()
```suggestion
const socket = connect()
```
lub
```suggestion
let socket = connect()
```

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/resources/game/js/websocket_connect.js
> +}
Warto wszystkie `var` zamienić na `let` lub `const`, analogicznie, gdy w ogóle nie ma explicite napisanego `var` (jest domyślnie).

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/core/player.py
> +    socket: WebSocket
1. Potrzebujemy tych dwóch linijek? Co dodają?
2. Jeśli mają zostać, to może warto je dać nad konstruktor, jeśli to są pola klasy.

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/core/room.py
> +from typing import Dict
Fajne to! 😄 Byłoby spoko, gdybyśmy wszyscy używali, ale pewnie będzie ciężko 😉

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/core/room.py
> +from starlette.websockets import WebSocketDisconnect
Jeśli się da, to można zamienić `starlette` na `fastapi`, ale to pierdoooła

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/core/server.py
> +    _rooms: Dict[int, Room]
Takie samo pytanie, jak w player.py, ostatnia linia jest tylko do zaznaczenia typu zmiennej `_rooms`?

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/resources/js/main.js
> +}
Tak samo, `var` -> `let` lub `const`

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/routers.py
> +    return HTMLResponse(f.read())
Te dwie funkcje robią tak naprawdę dokładnie to samo, a jedyna różnica, to ścieżka do HTMLa. Byłoby spoko, jakby wyglądały tak samo (obojętnie czy tak jak pierwsza, czy tak jak druga, oba sposoby są spoko). Można też ewentualnie zrobić osobną funkcję w stylu `read_html`.

2020-05-12 16:17 UTC, kichel98 commented on blankiety_galantow/resources/game/js/main.js
> +// Recive message from websocket
```suggestion
// Receive message from websocket
```

2020-05-12 16:19 UTC, kichel98 commented on blankiety_galantow/resources/game/js/websocket_connect.js
> +    console.log("XDDD")
XDDD

2020-05-12 16:35 UTC, KyrietS commented on blankiety_galantow/app.py
> +# Creating FastApi instance and mounting static files
To Bartek, ale i tak należy się zastanowić nad sensem komentarzy typu "Creating server object" nad linijką `server = Server()`. Trochę się traci czas czytając takie komentarze oczywiste. Szybciej ogarniesz z kodu co się dzieje 😛

2020-05-12 16:42 UTC, KyrietS commented on blankiety_galantow/core/player.py
> +    socket: WebSocket
Właśnie też nie do końca rozumiem tych linii. One chyba są po do, żeby przy korzystaniu z obiektu `player.socket` podpowiadało, że pole `socket` jest typu `WebSocket`. Też bym wolał, aby to było w konstruktorze gdzieś wrzucone, ale nie sprawdzałem czy się da...

2020-05-12 16:45 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +from starlette.websockets import WebSocketDisconnect
Szukałem długo jak zaimportować ten nieszczęsny `WebSocketDisconnect`. Nigdzie nie ma dokumentacji co to jest wgl xD
W końcu znalazłem w issue w repo FastAPI ktoś wysłał przykładowy kod i właśnie tak zaimportował to. Można to poprawić 👍

2020-05-12 16:51 UTC, KyrietS commented on blankiety_galantow/resources/game/js/websocket_connect.js
> +    console.log("XDDD")
XDDD
```suggestion
```

2020-05-12 16:52 UTC, KyrietS commented on blankiety_galantow/app.py
> +# Creating FastApi instance and mounting static files
Ad. 1. Tak, do usunięcia. Folder o tej nazwie jest niestandardowy i zbyt ogólny (nazwa sugeruje, że wszystkie klasy tam muszą być)

2020-05-12 16:56 UTC, KyrietS commented on blankiety_galantow/resources/game/js/main.js
> +    data = JSON.parse(event.data)
```suggestion
    const data = JSON.parse(event.data)
```

2020-05-12 17:07 UTC, KyrietS commented on blankiety_galantow/resources/game/js/websocket_connect.js
> +}
Tutaj w ogóle użycie *Cookie* jest zupełnie niepotrzebne. Po co wysyłać to ciasteczko do serwera za każdym razem? Trzeba to przerobić na prosty [LocalStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) klucz-wartość, bez tego dziwnego parsowania ciasteczka 😄 
To co się dzieje w tej funkcji getCookie, to trochę magia i będzie z tego task ;D

`connect` zaraz poprawię

2020-05-12 17:18 UTC, KyrietS commented on blankiety_galantow/routers.py
> +    return HTMLResponse(f.read())
Rozwiązane w commitcie 9021f9d.

2020-05-12 17:26 UTC, KyrietS commented on blankiety_galantow/resources/game/js/websocket_connect.js
> +}
Issue #20 jest do przerobienia funkcji `getCookie`. Tymczasowo można chyba zatwierdzić tę brzydką wersję

2020-05-12 17:27 UTC, KyrietS commented on blankiety_galantow/resources/js/main.js
> +}
Issue #20. Tymczasowo zostawiamy

2020-05-12 17:28 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +from typing import Dict
Można próbować stosować typy zmiennych gdzie się da. Zobaczymy jak to wyjdzie 😉

2020-05-12 17:32 UTC, KyrietS commented on blankiety_galantow/core/player.py
> +    socket: WebSocket
Zrobiłem testy i te dodatkowe linijki są zbędne. PyCharm przynajmniej potrafi ogarnąć typ z samego konstruktora, w którym są oznaczone typy.

2020-05-12 17:35 UTC, KyrietS commented on blankiety_galantow/core/server.py
> +    _rooms: Dict[int, Room]
Usunięte w 2765026

2020-05-12 17:35 UTC, KyrietS commented on blankiety_galantow/core/player.py
> +    socket: WebSocket
Usunięte w 2765026

2020-05-12 18:05 UTC, kichel98 approved these changes

2020-05-12 19:24 UTC, merged