Feat/game master
kichel98/BlankietyGalantow pull request #46
Opened 2020-05-18 13:33 UTC by ketrab321

#40 
#44

2020-05-18 16:07 UTC, KyrietS requested changes
Kilka rzeczy

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/deck.py
>          self.text = deck_reader["treść"]
Skąd wy wytrzasnęliście tę praktykę dodawania domyślnych pól w klasie, które trzymają jedynie typ. Nadawajcie te typy normalnie xD
```suggestion
class WhiteCard:
    def __init__(self, card_id: int, deck_reader):
        self.id: int = id
        self.text: str = deck_reader["treść"]
```

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/deck.py
> +    gap_count: int
Do usunięcia. Można nadać typy w konstruktorze. Do tego nie mogę wstawić sugestii, bo konstruktor nie został zmieniony w tym branchu.

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/game_master.py
> +        self.black_card = black_deck.get_card()
Można nadać typy w konstruktorze, niepotrzebne powtórzenia zmiennych. Jedyne co może zostać poza konstruktorem, to zmienne, które maja jakąś domyślną wartość, np.
```python
players_hands: Dict[Player, List[WhiteCard]] = {}
cards_selected: Dict[Player, List[WhiteCard]] = {}

def __init__(...):
```

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/game_master.py
> +          pass
Game Master nie będzie przetwarzał czatu 😉  To rzecz zupełnie niezależna od rodzaju wybranej gry.

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/game_master.py
> +    async def fill_players_hand(self, player: Player):
Myląca liczba mnoga
```suggestion
        await self.fill_player_hand(player)
        await self.send_black_card(player)

    async def fill_player_hand(self, player: Player):
```

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +        await self.game_master.new_player(player)
Funkcja nazwana rzeczownikiem `new_player` sugeruje, że zwraca nowego gracza. Jeśli funkcja coś robi, np. dodaje gracza, to może być `add_new_player`.

Problem z takim dodawaniem graczy jest jednak inny i dużo poważniejszy. Obecnie `game_master` nie wie nic o wyjściu gracza z pokoju. Można go oczywiście poinformować jakimś komunikatem albo wywołaniem funkcji, ale problem tkwi w samym pomyśle trzymania dwóch niezależnych od siebie list graczy: jedna w `room` druga w `game_master`. One **zawsze** muszą być takie same. 

Ciągłe synchronizowanie może być bardzo męczące, ale jak nie będzie na to lepszego pomysłu, to trzeba to zrobić jakoś bezpiecznie. Sama synchronizacja może działać tak, że w konstruktorze `game_master` dostaje oryginalną listę graczy od `room`. Lista jest mutable i jak się ją wyśle do `game_master`a, to będzie się zmieniała automatycznie. Trzeba oczywiście pamiętać, aby poinformować Game Mastera, gdy lista graczy ulegnie zmianie, aby on to uwzględnił.

Np. funkcja `game_master.notify_player_left(player)` i `game_master.notify_player_joined(player)` (lub podobne) wywoływana przez `room` i niech sobie `game_master` zrobi co chce z tym fantem. 

Zanim ten branch wejdzie trzeba powyższy problem dobrze rozwiązać.

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +        self.game_master = GameMaster(white_deck, black_deck)
Po co klasie `Room` wiedza o tym jakie talie są używane przez Game Mastera? 😉 
Niech Game Master wczyta je sobie sam w konstruktorze. Jeśli kiedyś dodamy nowych Game Masterów, to każdy z nich będzie mógł mieć swoje unikalne zbiory kart, będzie mógł np. filtrować te rasistowskie itd. 

Na razie nie widzę potrzeby, aby `Room` wiedział o istnieniu kart.

2020-05-18 16:07 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +            self.game_master.process_message(player, data)
Podoba mi się ten pomysł kaskadowości. To co nie odbierze sam `Room` przekazujemy do Game Mastera 👍 .
W przyszłości moglibyśmy zrobić takie warstwy, np.:
```python
if self.chat.process_message(player, data):
    pass  # albo jakiś debug print
elif self.game_master.process_message(player, data):
    pass
```
Czyli `process_message` zwraca `True` jeśli wiadomość została "przechwycona" przez moduł i odebrana. Na razie to co jest wystarczy i jest super.

2020-05-18 16:13 UTC, KyrietS commented on blankiety_galantow/core/room.py
> +        await self.game_master.new_player(player)
**Uwaga** PR #42 wprowadza osobną funkcję obsługującą wyjście gracza z pokoju. Najpierw zmergujemy #42, bo zostało już zatwierdzone.

2020-05-18 17:34 UTC, KyrietS commented on blankiety_galantow/core/deck.py
>          self.text = deck_reader["treść"]
Ok, w oficjalnych docach Pythona jest przykład, gdzie wyciągają zmienną z konstruktora i definiują jej typ na poziomie klasy: https://www.python.org/dev/peps/pep-0526/#id9

Tak czy inaczej ustalanie typu w konstruktorze działa tak samo i nie powtarzamy zmiennych. Kwestia gustu pewnie

2020-05-18 18:58 UTC, ketrab321 commented on blankiety_galantow/core/room.py
> +        await self.game_master.new_player(player)
Proponuję rozwiązanie problemu poprzez użycie wzorca observer i stworzenie obserwowalnej listy graczy w Roomie, która będzie obserwował GameMaster ;) Odpowiednie zmiany już wrzuciłem na brancha, można się zapoznać. Jest to według mnie proste i eleganckie rozwiązanie.
Wystarczy w GameMasterze dziedziczyć po klasie Observer, wywołać w konstruktorze callback metodą `add_callback`, a tym callbacku obsłużyć zachowanie GameMastera gdy lista graczy się zmieni.
Następnie dodajemy GameMastera jako Observer do listy graczy. Przy użyciu którejś z funkcji `add_item`, `remove_item` czy `update_item` GameMaster będzie informowany o zmianie listy graczy ;).
Aby działała komunikacja przez websockety cały wzorzec Obserwera działa na funkcjach asynchronicznych i takich też oczekuje jako callbacki, ale nie wydaje to mi się wielkim problemem w naszym przypadku ;)

2020-05-19 13:06 UTC, KyrietS approved these changes
Teraz gicior

2020-05-19 13:06 UTC, merged