change the visibility of the settings buttons for non-admins #34
kichel98/BlankietyGalantow pull request #53
Opened 2020-05-20 23:28 UTC by sokolowskam

poprawiłam widoczność przycisków dla nie-adminów. #34

2020-05-21 07:43 UTC, KyrietS commented
Nie jestem pewien czy chodziło o całkowite wyłączenie ustawień dla nieadmina... Bo teraz żaden użytkownik nie może nawet zobaczyć jakie są obecne ustawienia włączone...

2020-05-21 08:01 UTC, KyrietS requested changes
1. Przycisk 'Cancel' może być włączony. Myślę, że wystarczy wyłączyć 'Zapisz' 😄 
2. Opcje są nadal "klikalne" dla nie-admina. Niby to pierdoła, ale jeśli gracz nie ma uprawnień by je zmieniać, to byłoby fajnie, gdyby inputy też były `disabled`.
3. Mogłabyś przy okazji przetłumaczyć **Cancel** na **Anuluj**? 😃 
4. Po dołączeniu do serwera, kiedy klient nie odebrał jeszcze *listy graczy* od serwera, zmienna `me` jest `undefined` i rzucany jest błąd przy napotkaniu `!me.admin`. Na razie to zostaw. Pomyślimy czy nie zrobić *Loader* na cały ekran gry, a nie tylko "stół" jak obecnie.

2020-05-22 15:42 UTC, sokolowskam commented
poprawiłam wedle Twoich sugestii, spójrz teraz :)

2020-05-23 13:17 UTC, KyrietS approved these changes
Teraz ok

2020-05-23 13:17 UTC, merged